import axios from "axios";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import PlayerThumbnail from "../components/PlayerThumbnail";

interface IPlayerData {
  name: string;
  team: string;
  years: number;
  SignedAge: number;
  averageValue: string;
  totalValue: string;
  period: string;
  position: string;
  playerImg: string;
}

const Home: NextPage = () => {
  const [data, setData] = useState<IPlayerData[]>([]);

  const getData = async () => {
    const response = await axios("http://localhost:3000/api/ranking");
    setData(response.data);
  };

  useEffect(() => {
    getData();
  }, []);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col justify-center items-center">
        <h1>MLB Top 100 FA Players</h1>
        <ul className="grid gap-4 grid-cols-4 grid-rows-3 text-center">
          {data?.map((player: IPlayerData, index: number) => (
            <PlayerThumbnail
              key={index}
              playerImg={player.playerImg}
              name={player.name}
            />
          ))}
        </ul>
      </main>
    </div>
  );
};

export default Home;
