import axios from "axios";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";

interface IPlayerData {
  name: string;
  team: string;
  years: number;
  SignedAge: number;
  averageValue: string;
  totalValue: string;
  period: string;
  position: string;
  playerImg: string;
}

const Home: NextPage = () => {
  const [data, setData] = useState<IPlayerData[]>([]);

  const getData = async () => {
    const response = await axios("http://localhost:3000/api/ranking");
    setData(response.data);
  };

  useEffect(() => {
    getData();
  }, []);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>MLB Best Players</h1>
        {data?.map((player: IPlayerData, index: number) => (
          <div key={index}>
            <Image src={player.playerImg} width={200} height={200} />
            <h1>{player.name}</h1>
          </div>
        ))}
      </main>
    </div>
  );
};

export default Home;
